FROM python:3.12-slim

WORKDIR /app

#copy our backend directory
COPY ./backend/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

#copy our backend directory
COPY ./backend/ .

EXPOSE 8000

CMD ["./setup.sh"]